/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.AccountBUS;
import BUS.Common;
import BUS.HoaDonBUS;
import DAO.HoaDonDAO;
import static DAO.HoaDonDAO.shd;
import DAO.MySQLConnect;
import DTO.AccountDTO;
import DTO.HoaDonDTO;
import DTO.KhachHangDTO;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class HoaDonGUI extends javax.swing.JFrame {
    
    public  static ArrayList<HoaDonDTO> Arr_HoaDon = new ArrayList<>();
    Double Tong = 0.0;
    String maHD = "HD";
    int check = 1;
    public HoaDonGUI() throws Exception {
        initComponents();
        dodata();
        
        setLocationRelativeTo(null);       
        setVisible(true);
//        setState(this.ICONIFIED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ngayBanDATE = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        tenKHTXT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        maHDTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tenNVTXT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hoaDonTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        discountTXT = new javax.swing.JTextField();
        vatTXT = new javax.swing.JTextField();
        totalTXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        thanhToanButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        maKHTXT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Phiếu Thanh Toán");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Ngày Bán:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Tên Khách Hàng:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mã Hoá Đơn:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tên Nhân Viên:");

        tenNVTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenNVTXTActionPerformed(evt);
            }
        });

        hoaDonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số lượng", "Đơn Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hoaDonTable.setToolTipText("");
        hoaDonTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                hoaDonTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        hoaDonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hoaDonTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hoaDonTable);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Discount:");

        discountTXT.setEnabled(false);
        discountTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountTXTActionPerformed(evt);
            }
        });

        vatTXT.setEnabled(false);

        totalTXT.setEnabled(false);
        totalTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTXTActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tổng Tiền:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("VAT:");

        thanhToanButton.setText("Thanh Toán");
        thanhToanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thanhToanButtonActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("ID_KH:");

        maKHTXT.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel10))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(discountTXT)
                                            .addComponent(vatTXT)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(totalTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(447, 447, 447)
                                .addComponent(thanhToanButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maHDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenNVTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maKHTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ngayBanDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tenKHTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(maHDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tenNVTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(ngayBanDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tenKHTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maKHTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(vatTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(discountTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(thanhToanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tenNVTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenNVTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenNVTXTActionPerformed

    private void hoaDonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoaDonTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hoaDonTableMouseClicked

    private void hoaDonTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_hoaDonTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_hoaDonTableAncestorAdded

    private void discountTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discountTXTActionPerformed

    private void totalTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTXTActionPerformed

    private void thanhToanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thanhToanButtonActionPerformed
        HoaDonBUS bus = new HoaDonBUS();
        try {
            HoaDonDTO hoadon = new HoaDonDTO();
            hoadon.setID_Hoadon(maHDTXT.getText());
            hoadon.setID_NhanVien(Login.idhienhanh);
            hoadon.setID_Khachhang(maKHTXT.getText());
            hoadon.setID_Giamgia(discountTXT.getText());
            hoadon.setThanhTien(Double.valueOf(totalTXT.getText()));
            hoadon.setNgaylap(ngayBanDATE.getDate().toString());
            bus.themHoaDon(hoadon);
        } catch (Exception ex) {
            Logger.getLogger(HoaDonGUI.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
//            HoaDonDAO dao = new HoaDonDAO();
//            try {
//                dao.them();
//                JOptionPane.showMessageDialog(this, "Thêm Thành Công!!");
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Thất Bại!!");
//            }
            
       dispose();
    }//GEN-LAST:event_thanhToanButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        XemThemKhachHangGUI xemThemKhachHang = new XemThemKhachHangGUI();
//        for(KhachHangDTO khachhang : xemThemKhachHang.Arr_chonkhachhang){
//            tenKHTXT.setText(khachhang.getTenKhachHang());
//        }
        xemThemKhachHang.setVisible(true);
//        tenKHTXT.requestFocus();
//        tenKHTXT.setText(Common.khhh.getTenKhachHang());
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void dodata() throws Exception{
        
        String header[] = {"STT","Mã Sản Phẩm","Tên Sản Phẩm","Số Lượng","Đơn Giá"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        int temp= 1;
        for(int i = 0 ; i < HomeUser.Arr_GioHang.size(); i++){
            Vector table=new Vector();
            table.add(temp+i);
            table.add(HomeUser.Arr_GioHang.get(i).getID_Product());
            table.add(HomeUser.Arr_GioHang.get(i).getName());
            table.add(HomeUser.Arr_GioHang.get(i).getAmount());
            table.add(HomeUser.Arr_GioHang.get(i).getPice());
            model.addRow(table);
            Tong = Tong + HomeUser.Arr_GioHang.get(i).getAmount()*HomeUser.Arr_GioHang.get(i).getPice();
        }
        hoaDonTable.setModel(model);
        CreateTxt();
    }
    
//    public ArrayList<HoaDonDTO> docHoaDon (){
//        HoaDonDTO ctHoaDon = new HoaDonDTO();
//        for(int i = 0 ; i < Arr_HoaDon.size() ; i++){
//            ctHoaDon.setID_Hoadon(maHDTXT.getText());
//            ctHoaDon.setID_NhanVien(Login.idhienhanh);
//            ctHoaDon.setID_Khachhang(tenKHTXT.getText());
//            ctHoaDon.setID_Giamgia(discountTXT.getText());
//            ctHoaDon.setThanhTien(Double.valueOf(totalTXT.getText()));
//            ctHoaDon.setNgaylap(ngayBanDATE.getDate().toString());
//            Arr_HoaDon.add(ctHoaDon);
//        }
//        return Arr_HoaDon;
//    }

    public void CreateTxt () throws SQLException, Exception{
        //------------- ten nv
        AccountBUS bus = new AccountBUS();
                try {
                    bus.docaccount();                            
                    for (AccountDTO account : AccountBUS.Arr_account){
                        if (Login.idhienhanh.equals(account.getId_nhanvien())){
                            tenNVTXT.setText(account.hoten);
                        }
                    }
                }catch(Exception ex){
                    
                }
        //----------
        //-------------------ma HD
        MySQLConnect conn = new MySQLConnect();
        HoaDonBUS bushd = new HoaDonBUS();
           System.out.println(shd);
                bushd.docHoaDon();
                int tmp=shd+1;
                maHD = maHD +tmp; 
//                for (HoaDonDTO hoadon : bushd.Arr_HoaDonBUS){
//                    
//                    if (hoadon.getID_Hoadon().equals(maHD)){
//                        maHD = maHD + conn.CountRow()+1; 
//                         System.out.println(conn.CountRow());       
//                        break;
//                      
//                           
//                    }
//                }
          
        //-------------------------------

        tenKHTXT.setText("Khách Lẻ");
        maKHTXT.setText("KL");
        maHDTXT.setEditable(false);
        maHDTXT.setText(maHD);
        vatTXT.setText("0%");
        discountTXT.setText("0%");
        totalTXT.setText(String.valueOf(Tong));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HoaDonGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(HoaDonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField discountTXT;
    private javax.swing.JTable hoaDonTable;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maHDTXT;
    public static javax.swing.JTextField maKHTXT;
    private com.toedter.calendar.JDateChooser ngayBanDATE;
    public static javax.swing.JTextField tenKHTXT;
    private javax.swing.JTextField tenNVTXT;
    private javax.swing.JButton thanhToanButton;
    private javax.swing.JTextField totalTXT;
    private javax.swing.JTextField vatTXT;
    // End of variables declaration//GEN-END:variables
}
